### PR TITLE
Speed up generation code for high angular momentum

### PR DESCRIPTION
**Pull request by peterbygrave**
For Hessian we need `-DLIBECPINT_MAX_L=7`, but the generation code often throw and bad_alloc due to running out of memory.

This PR switches `std::vector<Triple>` that gets sorted and made unique for a `std::set<Triple>` which is sorted and unique by construction.

### CODE REVIEW

**Comment by peterbygrave** [comment]
Oh something went wrong with being up to date with your master, let me fix that

**Comment by peterbygrave** [comment]
Thanks for the update @robashaw No worrying about getting this merged, I have build infrastructure working with `.patch` files anyway.

Sorry about the failing tests, I was only building in debug where everything passes. If you could tell me your hint it would help me fix this.

I am also happy for this to be declined as I don't really know the underlying algorithm (clearly since I made everything break :D  )

**Comment by peterbygrave** [comment]
bug found. my mistake. fix incoming.

**Comment by robashaw** [comment]
```std::set``` has stronger requirements on the objects that can go in it and how they have to behave than ```std::vector```. My hunch is that, with debug flags turned off, we're getting undefined behaviours when sorting/asserting uniqueness. Because of the way the generated code is accessed, this can then cause some serious numerical shenanigans. I'd need to look into it more though to be honest.

**Comment by peterbygrave** [comment]
wow the `Code Inspector` job found the issue as well

**Comment by robashaw** [comment]
Haha it's a relief that it's something simple. I'll do a proper review of this later today.

**Review by robashaw — APPROVED** [review]

**Pull request merged**
