### PR TITLE
replaced C-style arrays with std::vector

### PR DESCRIPTION
**Pull request by JensWehner**
I got `mismatched free/delete` errors in bessel.cpp

as `<vector>` is included anyway I just replaced the `double***` with nested `std::vectors`, performance wise it should not matter otherwise I can also replace them with the 2-index,3-index classes. 

Also fixed the copy constructor of `ECP` object.

### CODE REVIEW

**Comment by junghans** [comment]
@robashaw I would need this, too!

**Comment by robashaw** [comment]
Thanks for this. I need to run some benchmarking tests because even a tiny change in the efficiency of the Bessel function routines can massively slow down everything else. I'll try to do that soon

**Comment by JensWehner** [comment]
Sure, if we you want to make the tables fast then using your 2/3 index things should be much better, because less pointer indirections.

**Comment by JensWehner** [comment]
@robashaw any verdict? Thx

**Comment by nabbelbabbel** [comment]
Updating the current destructor also works. If the decision to switch to other containers is to involved:
```
	BesselFunction::~BesselFunction() {
                for (int i = 0; i < N+1; i++) {
                        for (int j = 0; j < TAYLOR_CUT + 1; j++)
                                delete[] dK[i][j];
                        delete[] K[i];
                        delete[] dK[i];
                }
		delete[] K;
		delete[] dK;
		delete[] C;
	}
```

**Comment by junghans** [comment]
@robashaw any news on this?

**Comment by robashaw** [comment]
I’m sorry that I’ve not responded yet, I’ve been ill, but I’ll try to have a look at it tonight.

**Comment by robashaw** [comment]
I have benchmarked several build cases and can see no discernible difference, as the compiler is essentially translating the vector-based exactly the same way as the C-array-based code. It is plausible this will not be the case for older compiler versions, but I'm making an executive decision to neither worry nor care about that. 

Thanks for the request and sorry for the delay.

**Comment by junghans** [comment]
Could make a new patch release as well?

**Comment by junghans** [comment]
@robashaw could you make another 1.0 release, I will like to package this fix for fedora.

**Pull request merged**
